print('hola')
nombre=input('como te llamas')
print('tu nombre es', nombre)
grado=input('cual es tu grado ')
print('vas en', grado)
grupo=input('en que grupo vas')
print('tu grupo es', grupo)
comidafav=input('cual es tu bomida favorita')
print('tu comida favorita es ', comidafav,'ok?... eww' )
print('bueno ultima cosa')
algoqdecir=input('que le quieres decir al maestro')
print('le dijiste al maestro', algoqdecir)